/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paletizacao.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import paletizacao.controller.CalculaPercentagemController;
import paletizacao.model.Artigo;
import paletizacao.persistance.inmemory.InMemoryRepositoryFactory;

/**
 *
 * @author Mac
 */
public class CalculaPercentagemUI extends javax.swing.JFrame {

    private CalculaPercentagemController ctr = new CalculaPercentagemController();
    
    /**
     * Creates new form CalculaPercentagemUI
     */
    public CalculaPercentagemUI() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        preenchLista();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listArtigos = new javax.swing.JList();
        qntTextField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kgR = new javax.swing.JRadioButton();
        gR = new javax.swing.JRadioButton();
        uniR = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listArtigos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listArtigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listArtigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listArtigos);

        qntTextField.setText("qnt");
        qntTextField.setEnabled(false);
        qntTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qntTextFieldFocusGained(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        jButton2.setText("Adicionar");

        kgR.setText("kg");
        kgR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kgRMouseClicked(evt);
            }
        });

        gR.setText("g");
        gR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gRMouseClicked(evt);
            }
        });

        uniR.setText("uni");
        uniR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uniRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kgR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gR)
                        .addGap(18, 18, 18)
                        .addComponent(uniR)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kgR)
                    .addComponent(gR)
                    .addComponent(uniR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listArtigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listArtigosMouseClicked
        qntTextField.setEnabled(true);
    }//GEN-LAST:event_listArtigosMouseClicked

    private void kgRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kgRMouseClicked
        qntTextField.setText("kg");
        uniR.setSelected(false);
        gR.setSelected(false);
        revalidate();
    }//GEN-LAST:event_kgRMouseClicked

    private void gRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gRMouseClicked
        qntTextField.setText("g");
        uniR.setSelected(false);
        kgR.setSelected(false);
        revalidate();
    }//GEN-LAST:event_gRMouseClicked

    private void uniRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uniRMouseClicked
        qntTextField.setText("uni");
        kgR.setSelected(false);
        gR.setSelected(false);
        revalidate();
    }//GEN-LAST:event_uniRMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void qntTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qntTextFieldFocusGained
        qntTextField.setText("");
    }//GEN-LAST:event_qntTextFieldFocusGained

    private void preenchLista() {
        DefaultListModel listModel = new DefaultListModel();
        
        List<Artigo> art = InMemoryRepositoryFactory.getInstance().getArtigosRepository().getAll();
        
        for(Artigo a:art) {
            listModel.addElement(a);
        }
        
        listArtigos.setModel(listModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton gR;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton kgR;
    private javax.swing.JList listArtigos;
    private javax.swing.JTextField qntTextField;
    private javax.swing.JRadioButton uniR;
    // End of variables declaration//GEN-END:variables
}
